### PR TITLE
"Added contact popup modal"

### LINKED ISSUE #19: Add a contact pop-up modal with a form for clients to request your services

### PR DESCRIPTION
**Pull request by aswinikalyan30**
Closes #19 
ezgif-2-f757df76a2
Hey, i did some changes to the ui! If anything else has to be changed, please let me know!

### CODE REVIEW

**Comment by AmreshSinha** [comment]
Can you add some padding from left and right. Those elements are sticking to the boundary.

**Comment by aswinikalyan30** [comment]
image

**Comment by aswinikalyan30** [comment]
image

**Comment by aswinikalyan30** [comment]
hey, updates on this?

**Comment by aswinikalyan30** [comment]
Hey could you either merge/discard this PR?

**Pull request closed without merging**
